# FIELDS_DICT - יש להשתמש אך ורק בשמות מה־DICT הזה בכל מקום בקוד, בטבלאות, וב־API!
# אין להמציא שמות חדשים או לשנות שמות קיימים ללא עדכון ה־DICT!
# כל שינוי/הוספה/עדכון של שדה יתבצע רק כאן.

FIELDS_DICT = {
    # --- טבלת משתמשים ---
    "age": "גיל",
    "pronoun_preference": "לשון פניה (את/אתה/מעורב)",
    "occupation_or_role": "עיסוק (מה עושה בחיים?)",
    "attracted_to": "משיכה לגברים/נשים/שניהם (ועוד אופציות)",
    "relationship_type": "מצב זוגי / משפחתי (כולל ילדים)",
    "self_religious_affiliation": "יהדות/ערבי/דרוזי/נוצרי/אתאיסט וכו'",
    "self_religiosity_level": "רמת דתיות",
    "family_religiosity": "רמת דתיות משפחתית",
    "closet_status": "האם בארון / יצא / חלקי",
    "who_knows": "מי יודע עליו",
    "who_doesnt_know": "מי לא יודע עליו",
    "attends_therapy": "האם הולך לטיפול פסיכולוגי/רגשי/קבוצה כרגע?",
    "primary_conflict": "הסיפור / קונפליקט המרכזי שלו בחיים כרגע",
    "trauma_history": "טראומות אם ציין (להתנסח בזהירות ובעדינות ועם הרחבה)",
    "goal_in_course": "מה הוא רוצה שיקרה לו מהקורס (המטרות ששם לעצמו)",
    "language_of_strength": "משפטים מחזקים שהוא משתמש בהם (מה עוזר לו בזמנים קשים?)",
    "date_first_seen": "מתי התחילה השיחה איתו",
    "coping_strategies": "מה מרים אותך? מה עוזר לך להתמודד?",
    "fears_concerns": "פחדים וחששות",
    "future_vision": "מה החזון לעתיד",
    "last_update": "מתי עודכנה השורה לאחרונה (מתעדכן אוטומטית)",
    "summary": "ת.ז רגשית בסיסית שנשלחת בכל הודעה לGPT כרקע חשוב על המשתתף",

    # --- טבלת הודעות ---
    "message_id": "מזהה הודעה",
    "chat_id": "מזהה משתמש",
    "user_msg": "הודעת המשתמש",
    "user_summary": "תמצות הודעת המשתמש",
    "bot_reply": "תשובת הבוט",
    "bot_summary": "סיכום תשובת הבוט",
    "total_tokens": "סך כל הטוקנים",
    "prompt_tokens_total": "סך טוקנים בפרומט",
    "completion_tokens_total": "סך טוקנים בתשובה",
    "cached_tokens": "טוקנים במטמון",
    "total_cost_usd": "עלות סופית בדולר",
    "total_cost_ils": "עלות סופית באגורות",
    "usage_prompt_tokens_GPT1": "טוקנים פרומט - GPT ראשי",
    "usage_completion_tokens_GPT1": "טוקנים תשובה - GPT ראשי",
    "usage_total_tokens_GPT1": "סך טוקנים - GPT ראשי",
    "cached_tokens_gpt1": "כמה מתוכם זה קשד",
    "cost_gpt1": "כמה עלתה הקריאה באגורות",
    "model_GPT1": "מודל GPT ראשי",
    "usage_prompt_tokens_GPT2": "טוקנים פרומט - GPT מקצר",
    "usage_completion_tokens_GPT2": "טוקנים תשובה - GPT מקצר",
    "usage_total_tokens_GPT2": "סך טוקנים - GPT מקצר",
    "cached_tokens_gpt2": "כמה מתוכם קשד",
    "cost_gpt2": "כמה עלה באגורות",
    "model_GPT2": "מודל GPT מקצר",
    "usage_prompt_tokens_GPT3": "טוקנים פרומט - GPT מחלץ",
    "usage_completion_tokens_GPT3": "טוקנים תשובה - GPT מחלץ",
    "usage_total_tokens_GPT3": "סך טוקנים - GPT מחלץ",
    "cached_tokens_gpt3": "כמה מתוכם קשד",
    "cost_gpt3": "כמה עלה באגורות",
    "model_GPT3": "מודל GPT מחלץ",
    "usage_prompt_tokens_GPT4": "טוקנים פרומט - GPT מיזוג חכם ת.ז רגשית",
    "usage_completion_tokens_GPT4": "טוקנים תשובה - GPT מיזוג חכם ת.ז רגשית",
    "usage_total_tokens_GPT4": "סך טוקנים - GPT מיזוג חכם ת.ז רגשית",
    "cached_tokens_GPT4": "כמה מתוכם קשד",
    "cost_GPT4": "כמה עלה באגורות",
    "model_GPT4": "מודל GPT מיזוג חכם ת.ז רגשית",
    "fields_updated_by_4gpt": "איזה פריטים חדשים נשמרו מGPT 3  או 4",
    "timestamp": "טיימסטפ של ההודעה",
    "date_only": "תאריך בלבד של ההודעה",
    "time_only": "שעה בלבד של ההודעה"
} 