# Render Blueprint – minimal worker definition
# Note: Overlapping Deploy Policy is a workspace-level toggle in the dashboard;
# it cannot be set here, so follow the manual steps described separately.
services:
  - type: worker
    name: telegram-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"