# =============================================================
# Render Blueprint – Infrastructure-as-Code for this repository
# =============================================================
#
# This file lets Render recreate / update the live service purely
# from code. Commit any further infra changes here and open a PR.
#
# ────────────────────────────────────────────────────────────────
# Overlapping Deploy Policy
# ------------------------
# Render's "Overlapping Deploy Policy" (Override vs Wait) is a **workspace
# setting** – it cannot be defined in render.yaml.  After syncing this
# blueprint, open **Workspace → Settings → Overlapping Deploy Policy** in the
# Render dashboard and switch the policy to **Wait (queue newest deploy)** so
# that new deploys never cancel ones already running.
#
# The comment above is solely to document the desired behaviour in-repo.
# ────────────────────────────────────────────────────────────────

services:
  # Background worker that runs the Telegram bot
  - type: worker               # No public HTTP port required
    name: telegram-bot          # Visible name in the Render UI
    runtime: python             # Uses Render's native Python environment
    plan: starter               # 512 MB RAM – adjust if you need more

    # Git settings ------------------------------------------------
    repo: https://github.com/<your-org>/<your-repo>.git   # Change to real URL
    branch: main                   # Deploys from the main branch
    autoDeployTrigger: commit      # Redeploy on every commit that reaches main

    # Build & start commands -------------------------------------
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m bot.main   # Update if entry-point differs

    # Environment variables --------------------------------------
    envVars:
      # All secret tokens are provided interactively in the dashboard so they
      # never live in Git.
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_BOT_TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_NOTIFICATION_CHAT_ID
        sync: false

    # Optional: increase graceful-shutdown period (default 30 s)
    maxShutdownDelaySeconds: 120